# Generated by Django 3.1.7 on 2021-03-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(max_length=255)),
                ('regions', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
            ],
        ),
    ]
