# Generated by Django 3.1.7 on 2021-03-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRegion',
            fields=[
                ('region', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='courier',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('f', 'Foot'), ('b', 'Bike'), ('c', 'Car')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='courier',
            name='regions',
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(to='delivery.CourierRegion'),
        ),
    ]
