# Generated by Django 3.1.7 on 2021-03-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210325_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
            ],
        ),
    ]
